# Generated by Django 3.1.13 on 2022-01-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.district')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_Name', models.CharField(max_length=50)),
                ('vehicle_No', models.CharField(max_length=50)),
                ('driver_license_No', models.CharField(max_length=124)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Police_station', models.CharField(max_length=130)),
                ('Issuing_officer_Name', models.CharField(max_length=20)),
                ('Nature_of_Offence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.offence')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.district')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.location')),
            ],
        ),
    ]
