# Generated by Django 3.1.13 on 2022-03-20 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 20, 19, 15, 13, 346035)),
        ),
    ]
