# Generated by Django 3.1.13 on 2022-04-18 15:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_auto_20220320_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 18, 20, 33, 21, 713265)),
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime(2022, 4, 18, 20, 33, 21, 713265))),
                ('Reporter_name', models.CharField(max_length=20)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.district')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officer.location')),
            ],
        ),
    ]
