# Generated by Django 3.1.13 on 2022-04-26 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_auto_20220418_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='images_of_accident',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 13, 22, 57, 476022)),
        ),
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 13, 22, 57, 476022)),
        ),
    ]
