# Generated by Django 3.1.13 on 2022-04-26 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_auto_20220426_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='images_of_accident',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 13, 36, 36, 893206)),
        ),
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 13, 36, 36, 893206)),
        ),
    ]
