# Generated by Django 3.1.13 on 2022-03-08 16:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officer', '0004_auto_20220213_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='offence',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fine',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 8, 21, 56, 15, 490588)),
        ),
    ]
