# Generated by Django 3.1.13 on 2022-04-26 11:16

import datetime
from django.db import migrations, models
import officer.models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_auto_20220426_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='images_of_accident',
            field=models.ImageField(blank=True, null=True, upload_to=officer.models.filepath),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 16, 46, 50, 198011)),
        ),
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 26, 16, 46, 50, 198011)),
        ),
    ]
