# Generated by Django 3.1.13 on 2022-04-28 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_auto_20220426_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='images_of_accident',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accident',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 10, 19, 26, 459181)),
        ),
        migrations.AlterField(
            model_name='fine',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 10, 19, 26, 458203)),
        ),
    ]
