# Generated by Django 3.1.13 on 2022-03-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20220314_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('complainer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('complain', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 17, 18, 18, 38, 261554)),
        ),
    ]
