# Generated by Django 3.1.13 on 2022-04-28 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20220320_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 28, 10, 19, 26, 460175)),
        ),
    ]
