# Generated by Django 3.1.13 on 2022-01-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20220120_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='location',
            new_name='driver_license_No',
        ),
    ]
