# Generated by Django 3.1.13 on 2022-02-26 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='id',
        ),
        migrations.AlterField(
            model_name='codes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
